{{- if .Values.registration }}
apiVersion: v1
kind: Secret
metadata:
  name: telegram-appservices
  labels:
    {{- include "mautrix-telegram.labels" . | nindent 4 }}
stringData:
  registration.yaml: {{ .Values.registration | quote }}
  {{- if .Values.doublepuppetRegistration }}
  doublepuppet.yaml: {{ .Values.doublepuppetRegistration | quote }}
  {{- end }}
{{- end }}
